### PR TITLE
Merge pull request #12 from Kristi-D/master

### PR DESCRIPTION
**Pull request by WD40JS**
Conflict Merge

### CODE REVIEW

**Comment by WD40JS** [comment]
Merge

**Comment by WD40JS** [comment]
Merge

**Review by WD40JS — COMMENTED** [review]
Merge

**Review by WD40JS — COMMENTED** [review]
vergt4gh

**Comment by WD40JS** [comment]
ee

**Review by WD40JS — COMMENTED** [review]
sf

**Review by Kristi-D — APPROVED** [review]

**Pull request merged**
